-- 创建用户表 --
CREATE TABLE `t_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '名称',
  `dob` DATE NOT NULL DEFAULT '0000-00-00' COMMENT '出生日期',
  `address` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '地址',
  `description` VARCHAR(200) NOT NULL DEFAULT '0' COMMENT '描述',
  `phone` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '手机号',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间戳',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否删除 0未删除 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uniq_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户表';